package com.aeropush.events

enum class NativeProdEventType(val value: String) {
    DOWNLOAD_STARTED_PROD("DOWNLOAD_STARTED_PROD"),
    DOWNLOAD_ERROR_PROD("DOWNLOAD_ERROR_PROD"),
    DOWNLOAD_PROGRESS_PROD("DOWNLOAD_PROGRESS_PROD"),
    DOWNLOAD_COMPLETE_PROD("DOWNLOAD_COMPLETE_PROD"),
    SYNC_ERROR_PROD("SYNC_ERROR_PROD"),
    ROLLED_BACK_PROD("ROLLED_BACK_PROD"),
    INSTALLED_PROD("INSTALLED_PROD"),
    STABILIZED_PROD("STABILIZED_PROD"),
    EXCEPTION_PROD("EXCEPTION_PROD"),
    AUTO_ROLLED_BACK_PROD("AUTO_ROLLED_BACK_PROD");
}

enum class NativeStageEventType(val value: String) {
    DOWNLOAD_ERROR_STAGE("DOWNLOAD_ERROR_STAGE"),
    DOWNLOAD_PROGRESS_STAGE("DOWNLOAD_PROGRESS_STAGE"),
    DOWNLOAD_COMPLETE_STAGE("DOWNLOAD_COMPLETE_STAGE"),
    INSTALLED_STAGE("INSTALLED_STAGE");
}

object AeropushEventName {
    const val AEROPUSH_NATIVE_EVENT = "AEROPUSH_NATIVE_EVENT"
}
